#!/bin/bash
# Load usefull functions
if [ ! -f $HOME/scripto/bash/bash_library.sh ]; then
  echo "[error] $HOME/scripto/bash/bash_library.sh not found. Exiting. "
  exit 1
else
  . $HOME/scripto/bash/bash_library.sh
fi

INFO_MODE=DEBUG
#INFO_MODE=INFO

V_KEYSPACE=$1
check_parameter $V_KEYSPACE

CLITMPFILE=/tmp/dropKeyspace.tmp
# Get local Cassandra listen address.  Should be loaded via the selected
    # cassandra.yaml file above.
    if [ -z $listen_address ]; then
        CASIP=$( hostname )
    elif [ "$listen_address" == "0.0.0.0" ]; then
        CASIP=127.0.0.1
    else
        CASIP=$listen_address
    fi


printf "drop keyspace $V_KEYSPACE ;\n" > $CLITMPFILE

cqlsh $CASIP -f $CLITMPFILE
RC=$?

if [ $? -gt 0 ]; then
    printf "Keyspace drop failed.\n"
    exit 1
fi
