#!/usr/bin/expect -f
set timeout -1

set username [lindex $argv 0]
set hostname [lindex $argv 1]
set password_hash [lindex $argv 2]
set commands1 [lindex $argv 3]

set password [exec echo $password_hash | base64 --decode -i ]

#spawn ssh -t $username@$hostname "$commands1"
spawn scp $username@$hostname:"$commands1" .
sleep 1
#expect "password:"
expect "PASSCODE:"
send "$password\r"
sleep 1

expect eof
