#!/bin/bash
#$Id: o,v 1.1 2012-05-07 13:47:27 remik Exp $
#
# Setting oracle environment
#

# Load usefull functions
if [ ! -f $HOME/scripto/bash/bash_library.sh ]; then
  echo "[error] $HOME/scripto/bash/bash_library.sh not found. Exiting. "
  exit 1
else
  . $HOME/scripto/bash/bash_library.sh
fi

#INFO_MODE=DEBUG
RECIPIENTS='remigiusz_boguszewicz'
ORATAB=/var/opt/oracle/oratab

V_WHERE_DIALOG=`which `
# Find dialog
if [ -f /opt/csw/bin/dialog ]; then
  DIALOG=/opt/csw/bin/dialog
elif [ -f /opt/sfw/bin/dialog ]; then
  DIALOG=/opt/sfw/bin/dialog
fi

msgd "DIALOG: $DIALOG"

if [ -f "$DIALOG" ]; then
  msgd "OK, dialog found"
else
  msge "dialog NOT found. Exiting"
  msge "unable to present nice menu, please do it manually"
  exit 0
fi

msgd "Analiza oratab"
F_TMP=/tmp/dialog.tmp
if [ -f "$ORATAB" ]; then
  # construct dialog parameters
  run_command_d "cat $ORATAB"
  V_ORATAB_LINE=`cat $ORATAB | grep -v "^#" | awk '{print $0 " "$0}' | tr "\n" " "`
  #dialog --menu "Chose database" 15 65 5 1 "zzz" 2 "bbb" 2> $F_TMP
  #dialog --menu "Chose database" 15 65 5 "bbb" "bbb" 2> $F_TMP
  #dialog --menu "Chose database" 15 65 5 bbb bb 2> $F_TMP
  dialog --menu "Chose database:" 20 75 12 $V_ORATAB_LINE 2> $F_TMP
  V_CHOSEN_MENU=`cat $F_TMP`
  msgd "V_CHOSEN_MENU: $V_CHOSEN_MENU"
  V_CHOSEN_SID=`echo $V_CHOSEN_MENU | awk -F":" '{print $1}'`
  msgd "V_CHOSEN_SID: $V_CHOSEN_SID"
  V_CHOSEN_BIN=`echo $V_CHOSEN_MENU | awk -F":" '{print $2}'`
  msgd "V_CHOSEN_BIN: $V_CHOSEN_BIN"
  msgd "OK, now I should source the .profile found in selected binaries and set the ORACLE_SID"
 
  if [ -f "$V_CHOSEN_BIN/.profile" ]; then
    msgd "Sourcing .profile from $V_CHOSEN_BIN."
    . $V_CHOSEN_BIN/.profile
    msgd "ORACLE_SID: $V_CHOSEN_SID"
    export ORACLE_SID=$V_CHOSEN_SID
    
    # Setting handy aliases
    alias dbs='cd $ORACLE_HOME/dbs'
    alias tns='cd $ORACLE_HOME/network/admin'
    alias udump='cd /ORABIN/diag/$ORACLE_SID/udump'
    alias bdump='cd /ORABIN/diag/$ORACLE_SID/bdump'
    alias atail='tail -f /ORABIN/diag/$ORACLE_SID/bdump/alert_${ORACLE_SID}.log'
    alias ltail='less /ORABIN/diag/$ORACLE_SID/bdump/alert_${ORACLE_SID}.log'
    alias dba='sqlplus "/ as sysdba"'

    # Info section
    msgi "ORACLE_SID: $ORACLE_SID"
    msgi "ORACLE_HOME: $ORACLE_HOME"
    msgi 'List of alias:'
    alias

  else
    msge "There should exist .profile in $V_CHOSEN_BIN. Not found. Weird. Exiting."
    return 0
  fi #$V_CHOSEN_BIN/.profile

else
  msge "/var/opt/oracle/oratab NOT found. Exiting"
  exit 1
fi #oratab







