NAME=TEST10.db 
TYPE=cluster_resource 
DESCRIPTION=Oracle Database resource 
ACL=owner:oracle:rwx,pgrp:oinstall:rwx,other::r-- 
ACTION_SCRIPT=/u01/app/oracle/product/10.2.0/OC_RBO_active_passive_10g.sh
PLACEMENT=restricted 
ACTIVE_PLACEMENT=0 
AUTO_START=restore 
CARDINALITY=1 
CHECK_INTERVAL=10 
DEGREE=1 
ENABLED=1 
HOSTING_MEMBERS=usera1 usera2
LOGGING_LEVEL=1 
RESTART_ATTEMPTS=1 
START_DEPENDENCIES=hard(ora.DATA.dg) weak(type:ora.listener.type,uniform:ora.ons,uniform:ora.eons) pullup(ora.DATA.dg) 
START_TIMEOUT=600 
STOP_DEPENDENCIES=hard(intermediate:ora.asm,shutdown:ora.DATA.dg)
STOP_TIMEOUT=600 
UPTIME_THRESHOLD=1h
