select	
	TO_CHAR(SQ_GL_JE_HDR.JE_BATCH_ID)||'~'||TO_CHAR(SQ_GL_JE_HDR.JE_HEADER_ID)||'~'||TO_CHAR(SQ_GL_JE_HDR.JE_LINE_NUM)||'~'||TO_CHAR(SQ_GL_JE_HDR.GL_SL_LINK_ID)||'~'||SQ_GL_JE_HDR.GL_SL_LINK_TABLE	   C13_INTEGRATION_ID,
	SQ_GL_JE_HDR.BATCH_NAME	   C1_BATCH_NAME,
	SQ_GL_JE_HDR.HEADER_NAME	   C2_HEADER_NAME,
	SQ_GL_JE_HDR.STATUS	   C3_STATUS,
	SQ_GL_JE_HDR.JE_HEADER_ID	   C4_JE_HEADER_ID,
	SQ_GL_JE_HDR.JE_LINE_NUM	   C5_JE_LINE_NUM,
	SQ_GL_JE_HDR.JE_SOURCE	   C6_JE_SOURCE,
	SQ_GL_JE_HDR.JE_CATEGORY	   C7_JE_CATEGORY,
	SQ_GL_JE_HDR.GL_SL_LINK_ID	   C8_GL_SL_LINK_ID,
	SQ_GL_JE_HDR.GL_SL_LINK_TABLE	   C9_GL_SL_LINK_TABLE,
	SQ_GL_JE_HDR.LEDGER_ID	   C10_GL_LEDGER_ID,
	SQ_GL_JE_HDR.LEDGER_CATEGORY_CODE	   C11_GL_LEDGER_CATEGORY_CODE,
	SQ_GL_JE_HDR.END_DATE	   C12_GL_PER_END_DT,
	SQ_GL_JE_HDR.LAST_UPDATE_DATE	   C14_LAST_UPDATE_DATE
from	
( /* Subselect from SDE_ORA_PersistedStage_GLLinkageInformation_GLExtract.W_ORA_GL_LINKAGE_GL_JRNL_PS_SQ_GL_JE_HDR
*/
select 
	   T.LEDGER_ID LEDGER_ID,
	T.LEDGER_CATEGORY_CODE LEDGER_CATEGORY_CODE,
	PER.END_DATE END_DATE,
	GLIMPREF.JE_LINE_NUM JE_LINE_NUM,
	GLIMPREF.JE_HEADER_ID JE_HEADER_ID,
	GLIMPREF.GL_SL_LINK_TABLE GL_SL_LINK_TABLE,
	GLIMPREF.GL_SL_LINK_ID GL_SL_LINK_ID,
	JHEADER.NAME HEADER_NAME,
	JHEADER.STATUS STATUS,
	JBATCH.NAME BATCH_NAME,
	JHEADER.JE_SOURCE JE_SOURCE,
	JHEADER.JE_CATEGORY JE_CATEGORY,
	JHEADER.LAST_UPDATE_DATE LAST_UPDATE_DATE,
	JBATCH.JE_BATCH_ID JE_BATCH_ID
from	APPS.GL_JE_BATCHES AS OF TIMESTAMP to_timestamp('&1','YYYY-MM-DD--HH24:MI:SS') JBATCH,
APPS.GL_JE_HEADERS AS OF TIMESTAMP to_timestamp('&1','YYYY-MM-DD--HH24:MI:SS') JHEADER,
APPS.GL_IMPORT_REFERENCES AS OF TIMESTAMP to_timestamp('&1','YYYY-MM-DD--HH24:MI:SS') GLIMPREF,
APPS.GL_LEDGERS AS OF TIMESTAMP to_timestamp('&1','YYYY-MM-DD--HH24:MI:SS') T, 
APPS.GL_PERIODS AS OF TIMESTAMP to_timestamp('&1','YYYY-MM-DD--HH24:MI:SS') PER 
where	(1=1)
 And (JHEADER.LEDGER_ID=T.LEDGER_ID)
AND (JHEADER.JE_HEADER_ID=GLIMPREF.JE_HEADER_ID)
AND (JBATCH.JE_BATCH_ID=JHEADER.JE_BATCH_ID)
AND (T.PERIOD_SET_NAME=PER.PERIOD_SET_NAME)
AND (JHEADER.PERIOD_NAME=PER.PERIOD_NAME)
And (('NULL' IN ('2022,2061,2070,2072,2074,2076,2094,2096,2098,2120,2146,2248')
       OR ( 'NULL' NOT IN ('2022,2061,2070,2072,2074,2076,2094,2096,2098,2120,2146,2248')
           AND T.LEDGER_ID IN (2022,2061,2070,2072,2074,2076,2094,2096,2098,2120,2146,2248)
          )
)
AND
('__NONE__'  IN ('PRIMARY','SECONDARY','ALC_TRANSACTION','ALC_BALANCE','ALC','NONE')
       OR (   '__NONE__' NOT IN ('PRIMARY','SECONDARY','ALC_TRANSACTION','ALC_BALANCE','ALC','NONE')
           AND T.LEDGER_CATEGORY_CODE IN ('PRIMARY','SECONDARY','ALC_TRANSACTION','ALC_BALANCE','ALC','NONE')
          )
))
 And (GLIMPREF.GL_SL_LINK_ID IS NOT NULL)
 And (
 JHEADER.LAST_UPDATE_DATE>=TO_DATE(SUBSTR('2016-10-17 04:00:01',0,19),'YYYY-MM-DD HH24:MI:SS')
)
)   SQ_GL_JE_HDR
where	(1=1)
--and TO_CHAR(SQ_GL_JE_HDR.JE_HEADER_ID) = '4303929'
and TO_CHAR(SQ_GL_JE_HDR.JE_BATCH_ID)='232246'
--||'~'||TO_CHAR(SQ_GL_JE_HDR.JE_HEADER_ID)||'~'||TO_CHAR(SQ_GL_JE_HDR.JE_LINE_NUM)||'~'||TO_CHAR(SQ_GL_JE_HDR.GL_SL_LINK_ID)||'~'||SQ_GL_JE_HDR.GL_SL_LINK_TABLE in 
--('228639~4274031~4~15284079~XLAJEL'
--'228639~4274031~3~15284081~XLAJEL',
--'228639~4274031~1~15284082~XLAJEL',
--'228639~4274031~2~15284080~XLAJEL')
;
