PROMPT THIS SCRIPT WILL CAUSE A LOT OF TORUBLE!!!
PROMPT DON'T RUN IT IN PRODUCTION!!!
PAUSE PRESS ENTER TO CONTINUE OR CTRL+C TO EXIT...

DECLARE
  j number;
BEGIN
  WHILE true LOOP
    select count(*) into j from x$ksmsp;
  END LOOP;
END;
/

