DROP TABLE t1;
DROP TABLE t2;

CREATE TABLE t1(a INT PRIMARY KEY);
CREATE TABLE t2(b INT, c INT, FOREIGN KEY (c) REFERENCES t1(a));

INSERT INTO t1 SELECT rownum FROM dual CONNECT BY LEVEL<=10;
INSERT INTO t2 SELECT rownum, MOD(rownum,9)+1 FROM dual CONNECT BY LEVEL <= 100;

COMMIT;

UPDATE t2 SET c = 10 WHERE c = 1;

-- in another session run:
-- UPDATE t1 SET a = 7 WHERE a = 6;

