set linesize 300
set echo off
col FLASHBACK_SIZE format 999999999999
col OLDEST_FLASHBACK_TIME format a30
PROMPT OLDEST CURRENT TIME TO WHICH YOU CAN FLASHBACK DATABASE ;
select OLDEST_FLASHBACK_TIME,RETENTION_TARGET from  V$FLASHBACK_DATABASE_LOG;

PROMPT SIZE OF FLASHBACK DATA (MB);
select round(sum(BYTES)/1024/1024) "FLASHBACK SIZE (MB)" from V$FLASHBACK_DATABASE_LOGFILE;

PROMPT PERCENT OF USED SPACE IN RECOVERY AREA BY FLASHBACK LOGS;
select FILE_TYPE,PERCENT_SPACE_USED,PERCENT_SPACE_RECLAIMABLE,NUMBER_OF_FILES from V$FLASH_RECOVERY_AREA_USAGE where FILE_TYPE='FLASHBACKLOG';
exit;
