#!/bin/sh
# chkconfig: 345 99 10
# description: Oracle auto start-stop script.
#
# Set ORA_OWNER to the user id of the owner of the 
# Oracle database software.

ORA_OWNER=oracle

case "$1" in
    'start')
        # Start the Oracle databases:
 	ORA_SID=REMIK
        su - $ORA_OWNER -c "/home/oracle/scripto/oracle/start_stop/startup.sh $ORA_SID >> /var/tmp/start_$ORA_SID_`date -I`.log 2>&1"
        ;;
    'stop')
        # Stop the Oracle databases:
 	ORA_SID=REMIK
        su - $ORA_OWNER -c "/home/oracle/scripto/oracle/start_stop/shutdown.sh $ORA_SID >> /var/tmp/stop_$ORA_SID_`date -I`.log 2>&1"
        ;;
esac
