#!/bin/bash
# chkconfig: 345 20 80
# description: Start/Stop/restart script for Redis Sentinel

EXEC=/usr/local/bin/redis_R_VERSION/redis-server
PIDFILE="/var/run/sentinel_R_SENTINEL_UNIQUE_STR.pid"
CONF="/etc/redis/sentinel_R_SENTINEL_UNIQUE_STR/sentinel_R_SENTINEL_PORT.conf"

PID=`cat $PIDFILE 2> /dev/null`
case "$1" in
     start)
         echo "Starting sentinel R_SENTINEL_UNIQUE_STR ..."
         touch $PIDFILE
         exec $EXEC $CONF --sentinel --pidfile $PIDFILE
         ;;
     stop)
         echo "Stopping sentinel R_SENTINEL_UNIQUE_STR PID: $PID ..."
         kill $PID
         ;;
     restart)
         echo "Restarting sentinel R_SENTINEL_UNIQUE_STR ..."
         $0 stop
         sleep 2
         $0 start
         ;;
     *)
         echo "Usage $0 {start|stop|restart}"
         ;;
esac

